version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    container_name: estacionamento_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: tppe_user
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: db_estacionamento
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - estacionamento_network

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: estacionamento_app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_estacionamento?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-tppe_user}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-123456}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - estacionamento_network

  caddy_proxy:
    build:
      context: .
      dockerfile: frontend/caddy-proxy/Dockerfile
    container_name: estacionamento_frontend
    ports:
      - "3000:80"
    depends_on:
      - app 
    networks:
      - estacionamento_network

volumes:
  mysql_data:

networks:
  estacionamento_network:
    driver: bridge
