version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ttpe-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: estacionamento
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: ttpe-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app/target 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/estacionamento
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      
volumes:
  mysql_data: